### ISSUE TITLE
After running preprocess.py this error occured

### ISSUE THREAD

**Issue by jrebelsam** [picopalette/phishing-detection-plugin#1]
File "C:\Users\sam\Desktop\phishing-detection-plugin-1.0.01-beta\backend\dataset\preprocess.py", line 6, in <module>
    data = np.array(dataset['data'])
TypeError: 'generator' object is not subscriptable

**Comment by ramenhost** [comment]
Seems you have installed wrong arff module.
`pip install arff` installs [this](https://pypi.org/project/arff/). But the one that need to be installed is [this](https://pypi.org/project/liac-arff/).
Run
```
pip uninstall arff
pip install liac-arff
```
Better I add a **requirements.txt**
