### ISSUE TITLE
some sites that are legitimate, the extension pops out they are phish  

### ISSUE THREAD

**Issue by kalvineous** [picopalette/phishing-detection-plugin#3]
how can I improve the accuracy of the extension, in  some cases it gives a wrong information for the sites that are not malicious . thanks

**Comment by ramenhost** [comment]
Sorry for the terribly late reply. Hoping this will be helpful for others looking out to experiment with this.

This plugin is an implementation of [this paper](https://ieeexplore.ieee.org/abstract/document/8252051). 
Couple of options can be tried to improve precision such as better (updated) dataset, increasing number of features and the Random Forest model itself. However, these are out of scope for this implementation.

Feel free to re-open the issue if you want to discuss more on this.
