### ISSUE TITLE
Plugin is not supporting for the new chrome extensions

### ISSUE THREAD

**Issue by Anita-desire** [picopalette/phishing-detection-plugin#4]
Hello, I am facing some issues  while installing this GitHub repository in my system,
I am able to prepare the dataset successfully along with training the model and generating the classifier.json file but I faced issues while adding the plugin to my Chrome extensions.

The newer beta version crx file when I am trying to upload it in Chrome extensions is showing the error in the background scripts manifest file and I modified the code according to the manifest 3 version background.service_worker key then though I replaced it 
it is not working properly.

The plugin is not changing its values according to the websites It is always showing the default one which is 93% and the accuracy score and shows some errors where I am keeping the screenshots of errors I am facing through them. I am also attaching the picture of the manifest code that I have made changes in your code as it says the manifest is not supporting the background. scripts.

Image-1 :  (https://github.com/picopalette/phishing-detection-plugin/assets/105618883/e33c6099-991d-4d05-894d-286c0d254bec)
Image-2:  (https://github.com/picopalette/phishing-detection-plugin/assets/105618883/6db2395d-3d75-46b3-8e51-a257ec265b71)
Image-3: (https://github.com/picopalette/phishing-detection-plugin/assets/105618883/49b2c3c5-653d-41c1-8abd-c96b5b95c470)
![Plugin data process](https://github.com/picopalette/phishing-detection-plugin/assets/105618883/3e2fcbbd-6647-4079-a634-5e3d8c2c61cb)
![plugin error](https://github.com/picopalette/phishing-detection-plugin/assets/105618883/cdd7af66-877b-4c10-a7f4-bcc6461e2cfd)
![plugin error-1](https://github.com/picopalette/phishing-detection-plugin/assets/105618883/0bb9b1af-2575-4502-a0f7-f7a8644be519)
![plugin Training succesfully](https://github.com/picopalette/phishing-detection-plugin/assets/105618883/e9c92c57-fc2f-46ef-9b63-507da878fffd)
![plugin manifest](https://github.com/picopalette/phishing-detection-plugin/assets/105618883/d6acd12a-c180-4211-999c-f526484a9c01)

Operating System- Windows 11
Browser used: Google Chrome - Chrome version: Version 115.0.5790.173 (Official Build) (64-bit)

Please help by fixing these issues

**Comment by Anita-desire** [comment]
These the images of problems I faced while uploading it to the Chrome extension

![Plugin crx](https://github.com/picopalette/phishing-detection-plugin/assets/105618883/2b9999bf-4555-4623-a38a-5b3c1f4b51e4)
![plugin](https://github.com/picopalette/phishing-detection-plugin/assets/105618883/1d9cb260-99f6-4744-b63c-ac1584135cae)
![plugin-1](https://github.com/picopalette/phishing-detection-plugin/assets/105618883/d215bd1a-4811-44ca-8822-a52f73c39b96)

**Comment by ramenhost** [comment]
Chrome Manifest V3 has been updated. The background scripts need to be migrated to service worker model. Expect an update soon.

**Comment by Anita-desire** [comment]
Thank you for your response.I am eagerly waiting for the updated repository
code.

**Comment by ramenhost** [comment]
Feel free to reopen the issue if you still face the same error.

**Comment by Anita-desire** [comment]
![image](https://github.com/picopalette/phishing-detection-plugin/assets/105618883/961f57ee-1bf6-4668-894a-187f1fe4b21b)

still it is showing the error

**Comment by ramenhost** [comment]
I have updated wiki page for install instructions.  Crx loading is not recommended and hence you need to use "load unpacked" option and select `frontend` folder. Make sure to pull the latest code changes.

**Comment by ramenhost** [comment]
Hmm, I am unable to reproduce.
Can you once confirm that you don't have any local changes?

**Comment by Anita-desire** [comment]
yeah I didn't do any

**Comment by Anita-desire** [comment]
Are you able to reproduce it again?

**Comment by ramenhost** [comment]
### Few things to ensure
1. Remove the old plugin before loading the latest. 
2. Try disabling all other extensions to help find if they are interfering.

If above steps don't help, please share the following,
1. The URL you are testing with.
2. console output from the webpage tab (not the extensions page)
3. console output of the plugin service worker (Click `Inspect views service worker (Inactive)`) [Refer here](https://developer.chrome.com/docs/extensions/mv3/tut_debugging/#:~:text=%23-,Debug%20the%20service%20worker,-%23). Note: You need to open the console before loading the web page.

**Comment by ramenhost** [comment]
I figured out that the error you mention happens when the plugin is opened in `chrome://extensions` tab. If this is your case, please ignore this error. It should not happen if you don't open the plugin UI while being in `chrome://extensions` tab.

Ideally, we should include a check for this case and try to avoid this error. But considering this being an academic project, I would rather ignore this.

**Comment by Anita-desire** [comment]
I am sorry I tried to deploy the plugin in Microsoft browser instead google
but when I am testing on web pages it is not changing the values.

If you don't mind, can you send a demo video of how your plugin works and
how I need to see if it is working or not?

Please let me know .This is humble request don't mind asking like this
